DELETE FROM M_USER;
INSERT INTO M_USER VALUES ('user01', '申請者０１', 'pass', 'xxx@xxx.xx', '1', 0, 0, now(), 'system', now(), 'system');
INSERT INTO M_USER VALUES ('user02', '申請者０２', 'pass', 'xxx@xxx.xx', '1', 0, 0, now(), 'system', now(), 'system');
INSERT INTO M_USER VALUES ('user03', '申請者０３', 'pass', 'xxx@xxx.xx', '2', 0, 0, now(), 'system', now(), 'system');
INSERT INTO M_USER VALUES ('user04', '申請者０４', 'pass', 'xxx@xxx.xx', '2', 0, 0, now(), 'system', now(), 'system');
INSERT INTO M_USER VALUES ('user05', '申請者０５', 'pass', 'xxx@xxx.xx', '2', 0, 0, now(), 'system', now(), 'system');
INSERT INTO M_USER VALUES ('user06', '承認者０１', 'pass', 'xxx@xxx.xx', '1', 0, 0, now(), 'system', now(), 'system');
INSERT INTO M_USER VALUES ('user07', '承認者０２', 'pass', 'xxx@xxx.xx', '1', 0, 0, now(), 'system', now(), 'system');
INSERT INTO M_USER VALUES ('user08', '承認者０３', 'pass', 'xxx@xxx.xx', '1', 0, 0, now(), 'system', now(), 'system');
INSERT INTO M_USER VALUES ('user09', '承認者０４', 'pass', 'xxx@xxx.xx', '2', 0, 0, now(), 'system', now(), 'system');
INSERT INTO M_USER VALUES ('user10', '承認者０５', 'pass', 'xxx@xxx.xx', '2', 0, 0, now(), 'system', now(), 'system');
INSERT INTO M_USER VALUES ('user11', '管理者０１', 'pass', 'xxx@xxx.xx', '1', 0, 0, now(), 'system', now(), 'system');
commit;
