DELETE FROM M_USER_ROLE;
INSERT INTO M_USER_ROLE VALUES ('user01', 'ROLE_APPLY', 0, 0, now(), 'system', now(), 'system');
INSERT INTO M_USER_ROLE VALUES ('user02', 'ROLE_APPLY', 0, 0, now(), 'system', now(), 'system');
INSERT INTO M_USER_ROLE VALUES ('user03', 'ROLE_APPLY', 0, 0, now(), 'system', now(), 'system');
INSERT INTO M_USER_ROLE VALUES ('user04', 'ROLE_APPLY', 0, 0, now(), 'system', now(), 'system');
INSERT INTO M_USER_ROLE VALUES ('user05', 'ROLE_APPLY', 0, 0, now(), 'system', now(), 'system');
INSERT INTO M_USER_ROLE VALUES ('user06', 'ROLE_APPROVE', 0, 0, now(), 'system', now(), 'system');
INSERT INTO M_USER_ROLE VALUES ('user07', 'ROLE_APPROVE', 0, 0, now(), 'system', now(), 'system');
INSERT INTO M_USER_ROLE VALUES ('user08', 'ROLE_APPROVE', 0, 0, now(), 'system', now(), 'system');
INSERT INTO M_USER_ROLE VALUES ('user09', 'ROLE_APPROVE', 0, 0, now(), 'system', now(), 'system');
INSERT INTO M_USER_ROLE VALUES ('user10', 'ROLE_APPROVE', 0, 0, now(), 'system', now(), 'system');
INSERT INTO M_USER_ROLE VALUES ('user11', 'ROLE_ADMIN', 0, 0, now(), 'system', now(), 'system');
commit;
