DELETE FROM M_USER_APPROVE_FLOW;
INSERT INTO M_USER_APPROVE_FLOW VALUES ('user01', 1, 'user06', 0, 0, now(), 'system', now(), 'system');
INSERT INTO M_USER_APPROVE_FLOW VALUES ('user01', 2, 'user07', 0, 0, now(), 'system', now(), 'system');
INSERT INTO M_USER_APPROVE_FLOW VALUES ('user01', 3, 'user08', 0, 0, now(), 'system', now(), 'system');
INSERT INTO M_USER_APPROVE_FLOW VALUES ('user02', 2, 'user07', 0, 0, now(), 'system', now(), 'system');
INSERT INTO M_USER_APPROVE_FLOW VALUES ('user02', 3, 'user08', 0, 0, now(), 'system', now(), 'system');
INSERT INTO M_USER_APPROVE_FLOW VALUES ('user03', 3, 'user08', 0, 0, now(), 'system', now(), 'system');
INSERT INTO M_USER_APPROVE_FLOW VALUES ('user04', 3, 'user09', 0, 0, now(), 'system', now(), 'system');
INSERT INTO M_USER_APPROVE_FLOW VALUES ('user05', 1, 'user08', 0, 0, now(), 'system', now(), 'system');
INSERT INTO M_USER_APPROVE_FLOW VALUES ('user05', 3, 'user09', 0, 0, now(), 'system', now(), 'system');
commit;
