DELETE FROM M_USER_ROLE;
INSERT INTO M_USER_ROLE(user_id, role, version, del_flg, ins_date, ins_id, upd_date, upd_id) VALUES ('user01', 'ROLE_APPLY', 0, 0, now(), 'system', now(), 'system');
INSERT INTO M_USER_ROLE(user_id, role, version, del_flg, ins_date, ins_id, upd_date, upd_id) VALUES ('user02', 'ROLE_APPLY', 0, 0, now(), 'system', now(), 'system');
INSERT INTO M_USER_ROLE(user_id, role, version, del_flg, ins_date, ins_id, upd_date, upd_id) VALUES ('user03', 'ROLE_APPLY', 0, 0, now(), 'system', now(), 'system');
INSERT INTO M_USER_ROLE(user_id, role, version, del_flg, ins_date, ins_id, upd_date, upd_id) VALUES ('user04', 'ROLE_APPLY', 0, 0, now(), 'system', now(), 'system');
INSERT INTO M_USER_ROLE(user_id, role, version, del_flg, ins_date, ins_id, upd_date, upd_id) VALUES ('user05', 'ROLE_APPLY', 0, 0, now(), 'system', now(), 'system');
INSERT INTO M_USER_ROLE(user_id, role, version, del_flg, ins_date, ins_id, upd_date, upd_id) VALUES ('user06', 'ROLE_APPROVE', 0, 0, now(), 'system', now(), 'system');
INSERT INTO M_USER_ROLE(user_id, role, version, del_flg, ins_date, ins_id, upd_date, upd_id) VALUES ('user07', 'ROLE_APPROVE', 0, 0, now(), 'system', now(), 'system');
INSERT INTO M_USER_ROLE(user_id, role, version, del_flg, ins_date, ins_id, upd_date, upd_id) VALUES ('user08', 'ROLE_APPROVE', 0, 0, now(), 'system', now(), 'system');
INSERT INTO M_USER_ROLE(user_id, role, version, del_flg, ins_date, ins_id, upd_date, upd_id) VALUES ('user09', 'ROLE_APPROVE', 0, 0, now(), 'system', now(), 'system');
INSERT INTO M_USER_ROLE(user_id, role, version, del_flg, ins_date, ins_id, upd_date, upd_id) VALUES ('user10', 'ROLE_APPROVE', 0, 0, now(), 'system', now(), 'system');
INSERT INTO M_USER_ROLE(user_id, role, version, del_flg, ins_date, ins_id, upd_date, upd_id) VALUES ('user11', 'ROLE_ADMIN', 0, 0, now(), 'system', now(), 'system');
commit;
