----------------------------------------------
----論理名：月報管理ビュー
----物理名：v_report
----------------------------------------------
--create or replace view vt_report (
--  applicant_id
--  , applicant_nm
--  , target_ym
--  , target_year
--  , target_month
--  , applicant_date
--  , status
--  , status_nm
--  , approver1_id
--  , approver1_nm
--  , approver2_id
--  , approver2_nm
--  , approver3_id
--  , approver3_nm
--  , file_path
--  , del_flg
--  , ins_date
--  , ins_id
--  , upd_date
--  , upd_id
--) as
--select
--  R.applicant_id
--  , (select U.user_nm from M_USER U where R.applicant_id = U.user_id)
--  , R.target_ym
--  , left(R.target_ym, 4)
--  , right(R.target_ym, 2)
--  , R.applicant_date
--  , R.status
--  , (select C.code_nm from M_CODE C where C.code_kbn = 'A001' and R.status = C.code)
--  , R.approver1_id
--  , (select U.user_nm from M_USER U where R.approver1_id = U.user_id)
--  , R.approver2_id
--  , (select U.user_nm from M_USER U where R.approver2_id = U.user_id)
--  , R.approver3_id
--  , (select U.user_nm from M_USER U where R.approver3_id = U.user_id)
--  , R.file_path
--  , R.del_flg
--  , R.ins_date
--  , R.ins_id
--  , R.upd_date
--  , R.upd_id
--from
--  t_report R
--;
